language: node_js
node_js:
- node
script:
  - npm test
  - npm run build
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: cytkiEEp84H/1728jBRaqdTU61AEekwrP9h9vPCE6rFlQxptOIFOVTQTC9RekAtoRfa9vDWgiNOEcKk+MCXYitn1tHt03YfrvMSdgCWq2X1hrPfxKoe5C/YNee5rfm7Hk+L0IoagwA3f4gEf8RKUHhO3s2lRrCWxz5I0T6G5Wmy+8d5jbHTa3MrjN0jupE7lv9mNBcLVJkp8EYMernn+9xfkNcexKcbqGNCaqrO3G6HVw9+YCbDuLqzpPnsOWUJ4kM8/NEbkSxFaCyj3/iU7jpCNIXLC7Ca1jMJ4k45KY7oxLxqYhwwvUU0/XGCLu5MHgXDFZpGRWpoEamLoBGRWGgpGOtNH4v0dxJDK+JHmNFyxoAc+m2YiKqKXMIqAKsMUvuaNHDszlzfSs7j0KoCdWYBZLGgMdvTeuiAwCOlAUutiB1Y1OJjM0CHhb5r8qb5f7z7s+HHnAy3AC8VbHjwdeeAtwydE3Noai0EMTocrbFTPJ2u+ewqSx6kRbXK0QGir1FZBjKQpnhNwXSgmmr5tLWfh1gogvlS4QcCCtAOZv9T9mHwz5Ha8YVbUafqUMtN0r3aTEETeZfGvAnHgW+lffxYC38QkB1PuD97kVNHqarCOSIyAzE8JhklHhwymAIf3CHvHYud/VIZtT93s+RKSMNRY8fN8szGyxz6tLA8cuZc=
    app: top-vinyl-frontend
    skip_cleanup: true
