language: node_js
node_js:
- stable
script:
- npm test
- npm run build
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: XH6di7iF9GByrrf/qYDarMI43Pr/BlxP2atq4NGtujXxRTk42vTZjGqKAYMWO3UNzwVUBBJTwQsARnZXBy+ENuEK5XLkljjJa6etYii3DrZTn8DGmbIUzUedhNjecuRwvZU9kzrHPf2bgKfXJO2x45PuPNfJHriBRTZzVPSiq2s97LjBo3cW2rXLOsP2RYVHF8oK9XabAxq2prqjE2ue9n1yvux7wM+kmADaI2TD5/Uy7+EvjV3OUW+T3B0snlB0DbPIdHXFzQBSuaKZpqwoXjEZ0eyBZluOkqzoN+yR2R8VWGn0rUQ69U+++ZhbALe2Vb1EiA6GGLUFBZMTnOy0h8zNaHeI51QroqIZIgvOk2YzdD7jsJ++XPJjFBdAluflnjgIPTzWsuh14AaqSWcH97wApmcMrJEtFzo7CqlwG4+r7rlIRgGNE5Ft2vOfrtwwWiEqHs7Qd45DxeMsk0BYMt9eOD/JEc5WjwSGOZeOw42d995WVt8KjjywJkvK/F+MtaVltbN7iMCpWgMYI9v1/4a7yR4aSSZRudvA7HwjG+syNBW1W3PX6pkXp99AOs2fR3CisqVsjFFO/HQWgEEBTQh0tVmPz/zd9fcEdnKvEbGEitzh58zXyMQrCBb1xCk6MmroDqCnwpCGfR7Nvqm3QdvDAmMpjx/3jP/Ok/M/F/Q=